version = 0.1

[default]
[default.global.parameters]
stack_name = "dev"
region = "eu-west-1"
parameter_overrides = "Environment=dev"


[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[dev.deploy.parameters]
stack_name = "dev"
parameter_overrides = "Environment=\"dev\""
s3_prefix = "dev"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[staging.deploy.parameters]
stack_name = "staging"
parameter_overrides = "Environment=\"staging\""
s3_prefix = "staging"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "prod"
parameter_overrides = "Environment=\"prod\""
s3_prefix = "prod"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
