version = 0.1

[default]
[default.global.parameters]
stack_name = "dev"
region = "eu-west-1"
parameter_overrides = "Environment=dev"


[default.deploy.parameters]
resolve_s3 = true
s3_prefix = "dev"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []

[dev.deploy.parameters]
stack_name = "dev"
parameter_overrides = "Environment=\"dev\" VpcId=\"vpc-013618c4404fd46c9\" SubnetIds=\"subnet-0a2945f0be1085106,subnet-0bb7daca3e59b5cae\" SecurityGroupIds=\"sg-08bbf252a36a52f6f\""
s3_prefix = "dev"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[staging.deploy.parameters]
stack_name = "staging"
parameter_overrides = "Environment=\"staging\" VpcId=\"vpc-013618c4404fd46c9\" SubnetIds=\"subnet-0a2945f0be1085106,subnet-0bb7daca3e59b5cae\" SecurityGroupIds=\"sg-08bbf252a36a52f6f\""
s3_prefix = "staging"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[local.deploy.parameters]
stack_name = "local"
parameter_overrides = "Environment=\"local\" VpcId=\"vpc-013618c4404fd46c9\" SubnetIds=\"subnet-0a2945f0be1085106,subnet-0bb7daca3e59b5cae\" SecurityGroupIds=\"sg-08bbf252a36a52f6f\""
s3_prefix = "local"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false

[prod.deploy.parameters]
stack_name = "prod"
parameter_overrides = "Environment=\"prod\" VpcId=\"vpc-0fbf59f4fa68abaa0\" SubnetIds=\"subnet-091da1f82047f878b,subnet-0a709dd1eddbc24a0\" SecurityGroupIds=\"sg-05dc53df766e736eb\""
s3_prefix = "prod"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
