AWSTemplateFormatVersion: 2010-09-09
Description: traderapp-serverless-platform
Transform:
  - AWS::Serverless-2016-10-31

Metadata:
  BuildMethod: esbuild
  BuildProperties:
    Minify: true
    Target: es2020
    SourceMap: true
    InlineSourceMap: false
    External:
      - aws-sdk # Example of excluding the AWS SDK
    AbsWorkingDir: . # Root directory for absolute imports

Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name to prefix resources

Resources:
# create queues
  emailOtpQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-emailOtpQueue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt emailOtpDLQ.Arn
        maxReceiveCount: 3
  emailOtpDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-emailOtpDLQ
  
  emailNotificationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-emailNotificationsQueue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt emailNotificationsDLQ.Arn
        maxReceiveCount: 3
  emailNotificationsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-emailNotificationsDLQ

  userReferralsTrackingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-userReferralsTrackingQueue
      VisibilityTimeout: 90
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt userReferralsTrackingDLQ.Arn
        maxReceiveCount: 3
  userReferralsTrackingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-userReferralsTrackingDLQ

  cryptopayChannelsWebhooksQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-cryptopayChannelsWebhooksQueue
      VisibilityTimeout: 90
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt cryptopayChannelsWebhooksDLQ.Arn
        maxReceiveCount: 3
  cryptopayChannelsWebhooksDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-cryptopayChannelsWebhooksDLQ

  cryptopayInvoiceWebhooksQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-cryptopayInvoiceWebhooksQueue
      VisibilityTimeout: 90
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt cryptopayInvoiceWebhooksDLQ.Arn
        maxReceiveCount: 3
  cryptopayInvoiceWebhooksDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-cryptopayInvoiceWebhooksDLQ
 
  createUserWalletQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-createUserWalletQueue
      VisibilityTimeout: 90
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt createUserWalletDLQ.Arn
        maxReceiveCount: 3
  createUserWalletDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-createUserWalletDLQ

  updateUserOnboardingStatusQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-updateUserOnboardingStatusQueue
      VisibilityTimeout: 60
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt updateUserOnboardingStatusDLQ.Arn
        maxReceiveCount: 3
  updateUserOnboardingStatusDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${Environment}-updateUserOnboardingStatusDLQ

# create lambda functions
  sendEmailOtp:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-sendEmailOtp
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/send-email-otp.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt emailOtpQueue.Arn
      MemorySize: 128
      Timeout: 30
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt emailOtpDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:common-secrets/${Environment}*
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:notifications-service/${Environment}*

  sendEmailNotifications:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-sendEmailNotifications
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/send-email-notifications.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt emailNotificationsQueue.Arn
      MemorySize: 128
      Timeout: 60
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt emailNotificationsDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:notifications-service/${Environment}*

  userReferralsTracking:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-userReferralsTracking 
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/track-user-referrals.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt userReferralsTrackingQueue.Arn
      MemorySize: 128
      Timeout: 90
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt userReferralsTrackingDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:trading-engine-service-secrets/${Environment}*
              - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:users-service-secrets/${Environment}*
            
  processCryptopayChannelsWebhooks:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-processCryptopayChannelsWebhooks
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/process-cryptopay-channels-webhooks.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt cryptopayChannelsWebhooksQueue.Arn
      MemorySize: 128
      Timeout: 90
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt cryptopayChannelsWebhooksDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:wallets-service-secrets/${Environment}*
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:common-secrets/${Environment}*
            - Effect: Allow
              Action:
                - sqs::SendMessage
                - sqs::SendMessageBatch
              Resource:
                - !GetAtt updateUserOnboardingStatusQueue.Arn

  processCryptopayInvoiceWebhooks:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-processCryptopayInvoiceWebhooks
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/process-cryptopay-invoice-webhooks.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt cryptopayInvoiceWebhooksQueue.Arn
      MemorySize: 128
      Timeout: 90
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt cryptopayInvoiceWebhooksDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:wallets-service-secrets/${Environment}*

  createUserWallet:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-createUserWallet
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/create-user-wallet.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt createUserWalletQueue.Arn
      MemorySize: 128
      Timeout: 90
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt createUserWalletDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:common-secrets/${Environment}*
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:wallets-service-secrets/${Environment}*

  updateUserOnboardingStatus:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          ENV: !Ref Environment
      FunctionName: !Sub ${Environment}-updateUserOnboardingStatus
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Handler: dist/handlers/update-user-onboarding-status.handler
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt updateUserOnboardingStatusQueue.Arn
      MemorySize: 128
      Timeout: 60
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt updateUserOnboardingStatusDLQ.Arn
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:users-service-secrets/${Environment}*