common-secrets:
  EMAIL_OTP_QUEUE:
    queueName: "emailOtpQueue"
  EMAIL_NOTIFICATIONS_QUEUE:
    queueName: "emailNotificationsQueue"
  USER_REFERRALS_TRACKING_QUEUE:
    queueName: "userReferralsTrackingQueue"
  TRACK_USER_ONBOARDING_CHECKLIST_QUEUE:
    queueName: "trackUserOnboardingChecklistQueue"

wallets-service-secrets:
  CRYPTOPAY_CHANNELS_WEBHOOKS_QUEUE:
    queueName: "cryptopayChannelsWebhooksQueue"
  CRYPTOPAY_INVOICE_WEBHOOKS_QUEUE:
    queueName: "cryptopayInvoiceWebhooksQueue"
  CRYPTOPAY_WITHDRAWAL_WEBHOOKS_QUEUE:
    queueName: "cryptopayWithdrawalWebhooksQueue"

users-service-secrets:
  CREATE_USER_WALLET_QUEUE:
    queueName: "createUserWalletQueue"

trading-engine-service-secrets:
  PROCESS_INCOMING_MASTER_TRADES_QUEUE:
    queueName: "processIncomingMasterTradesQueue"
  PROCESS_USER_TRADES_QUEUE:
    queueName: "processUserTradesQueue"
  PROCESS_BINANCE_ORDERS_QUEUE:
    queueName: "processBinanceOrdersQueue"
  HANDLE_PROCESSED_TRADES_QUEUE:
    queueName: "handleProcessedTradesQueue"
  HANDLE_FAILED_TRADES_QUEUE:
    queueName: "handleFailedTradesQueue"