common-secrets:
  EMAIL_OTP_QUEUE:
    queueName: "emailOtpQueue"
  EMAIL_NOTIFICATIONS_QUEUE:
    queueName: "emailNotificationsQueue"
  USER_REFERRALS_TRACKING_QUEUE:
    queueName: "userReferralsTrackingQueue"