common-secrets:
  EMAIL_OTP_QUEUE:
    queueName: "emailOtpQueue"
  EMAIL_NOTIFICATIONS_QUEUE:
    queueName: "emailNotificationsQueue"
  USER_REFERRALS_TRACKING_QUEUE:
    queueName: "userReferralsTrackingQueue"
  TRACK_USER_ONBOARDING_CHECKLIST_QUEUE:
    queueName: "trackUserOnboardingChecklistQueue"

wallets-service-secrets:
  CRYPTOPAY_CHANNELS_WEBHOOKS_QUEUE:
    queueName: "cryptopayChannelsWebhooksQueue"
  CRYPTOPAY_INVOICE_WEBHOOKS_QUEUE:
    queueName: "cryptopayInvoiceWebhooksQueue"
  CRYPTOPAY_WITHDRAWAL_WEBHOOKS_QUEUE:
    queueName: "cryptopayWithdrawalWebhooksQueue"

users-service-secrets:
  CREATE_USER_RESOURCES_QUEUE:
    queueName: "createUserResourcesQueue"

trading-engine-service-secrets:
  PROCESS_INCOMING_MASTER_TRADES_QUEUE:
    queueName: "processIncomingMasterTradesQueue"
  PROCESS_USER_TRADES_QUEUE:
    queueName: "processUserTradesQueue"
  PROCESS_BINANCE_ORDERS_QUEUE:
    queueName: "processBinanceOrdersQueue"
  PROCESS_BYBIT_ORDERS_QUEUE:
    queueName: "processBybitOrdersQueue"
  HANDLE_PROCESSED_TRADES_QUEUE:
    queueName: "handleProcessedTradesQueue"
  HANDLE_FAILED_TRADES_QUEUE:
    queueName: "handleFailedTradesQueue"
  PROCESS_BYBIT_ORDERS_ACTIVATION_QUEUE:
    queueName: "processBybitOrdersActivationQueue"
  PROCESS_BYBIT_STOP_LOSS_ORDERS_QUEUE:
    queueName: "processBybitStopLossOrdersQueue"
  PROCESS_BYBIT_TAKE_PROFIT_ORDERS_QUEUE:
    queueName: "processBybitTakeProfitOrdersQueue"
  CLOSE_BYBIT_TRADES_QUEUE:
    queueName: "closeBybitTradesQueue"