name: traderapp-serverless-platform-deploy-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Allow manual runs of the pipeline.

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event_name == 'push' && github.ref_name }}

    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v2

      # - name: Set environment variables
      #   run: |
      #     echo "NODE_ENV=${{ vars.NODE_ENV }}" >> $GITHUB_ENV
      #     echo "SERVICE=${{ vars.SERVICE }}" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.0

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.event_name == 'push' && github.ref_name }}

    steps:
      - name: Checkout code from branch
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Deploy the service
        run: npm run deploy --config-env dev

      - name: Install dependencies
        run: npm install --force

      - name: Deploy secrets
        run: npm run deploy-secrets dev
